AllCops:
  TargetRubyVersion: 2.1.0

Layout/AlignParameters:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Lint/UnneededSplatExpansion:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/Alias:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20
